[project]
name = ""
version = ""
description = ""
authors = [
    {name = "KYHSGeekCode", email = "jourhyang123@gmail.com"},
]
dependencies = [
    "appdirs==1.4.4",
    "beautifulsoup4==4.12.2",
    "bs4==0.0.1",
    "certifi==2022.12.7",
    "charset-normalizer==3.1.0",
    "click==8.1.3",
    "cloudpickle==2.2.1",
    "contourpy==1.0.7",
    "cycler==0.11.0",
    "decorator==4.4.2",
    "dm-tree==0.1.8",
    "docker-pycreds==0.4.0",
    "einops==0.6.1",
    "entmax==1.1",
    "Farama-Notifications==0.0.4",
    "filelock==3.10.7",
    "fonttools==4.39.3",
    "fsspec==2023.6.0",
    "gitdb==4.0.10",
    "GitPython==3.1.31",
    "graphviz==0.20.1",
    "gym==0.26.2",
    "gym-notices==0.0.8",
    "gymnasium==0.28.1",
    "huggingface-hub==0.16.4",
    "idna==3.4",
    "imageio==2.28.1",
    "imageio-ffmpeg==0.4.8",
    "importlib-metadata==6.3.0",
    "importlib-resources==5.12.0",
    "jax-jumpy==1.0.0",
    "Jinja2==3.1.2",
    "kiwisolver==1.4.4",
    "kornia==0.7.0",
    "MarkupSafe==2.1.2",
    "matplotlib==3.7.1",
    "moviepy==1.0.3",
    "mpmath==1.3.0",
    "networkx==3.0",
    "numpy==1.24.2",
    "packaging==23.1",
    "pathtools==0.1.2",
    "Pillow==9.4.0",
    "proglog==0.1.10",
    "protobuf==4.22.3",
    "psutil==5.9.5",
    "pygame>=2.5.1",
    "pyparsing==3.0.9",
    "python-dateutil==2.8.2",
    "python-dotenv==1.0.0",
    "pyyaml>=6.0.1",
    "regex==2023.8.8",
    "requests==2.28.2",
    "safetensors==0.3.2",
    "sentencepiece==0.1.99",
    "sentry-sdk==1.21.0",
    "setproctitle==1.3.2",
    "six==1.16.0",
    "smmap==5.0.0",
    "soupsieve==2.4.1",
    "sympy==1.11.1",
    "tokenizers==0.13.3",
    "torch==2.0.0",
    "torchsummary==1.5.1",
    "torchview==0.2.6",
    "torchvision==0.15.1",
    "torchviz==0.0.2",
    "tqdm==4.65.0",
    "transformers==4.31.0",
    "typing-extensions==4.7.1",
    "urllib3==1.26.15",
    "wandb==0.15.4",
    "x-transformers==0.27.1",
    "zipp==3.15.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
